// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

/*
Package calculatorpb is a generated protocol buffer package.

It is generated from these files:
	calculator/calculatorpb/calculator.proto

It has these top-level messages:
	Numbers
	OperationRequest
	OperationResponse
	PrimeNumberDecompositionRequest
	PrimeNumberDecompositionResponse
*/
package calculatorpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Numbers struct {
	FirstNumber  float32 `protobuf:"fixed32,1,opt,name=first_number,json=firstNumber" json:"first_number,omitempty"`
	SecondNumber float32 `protobuf:"fixed32,2,opt,name=second_number,json=secondNumber" json:"second_number,omitempty"`
}

func (m *Numbers) Reset()                    { *m = Numbers{} }
func (m *Numbers) String() string            { return proto.CompactTextString(m) }
func (*Numbers) ProtoMessage()               {}
func (*Numbers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Numbers) GetFirstNumber() float32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *Numbers) GetSecondNumber() float32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type OperationRequest struct {
	Numbers *Numbers `protobuf:"bytes,1,opt,name=numbers" json:"numbers,omitempty"`
}

func (m *OperationRequest) Reset()                    { *m = OperationRequest{} }
func (m *OperationRequest) String() string            { return proto.CompactTextString(m) }
func (*OperationRequest) ProtoMessage()               {}
func (*OperationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OperationRequest) GetNumbers() *Numbers {
	if m != nil {
		return m.Numbers
	}
	return nil
}

type OperationResponse struct {
	Result float32 `protobuf:"fixed32,1,opt,name=result" json:"result,omitempty"`
}

func (m *OperationResponse) Reset()                    { *m = OperationResponse{} }
func (m *OperationResponse) String() string            { return proto.CompactTextString(m) }
func (*OperationResponse) ProtoMessage()               {}
func (*OperationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OperationResponse) GetResult() float32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type PrimeNumberDecompositionRequest struct {
	Number int32 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
}

func (m *PrimeNumberDecompositionRequest) Reset()                    { *m = PrimeNumberDecompositionRequest{} }
func (m *PrimeNumberDecompositionRequest) String() string            { return proto.CompactTextString(m) }
func (*PrimeNumberDecompositionRequest) ProtoMessage()               {}
func (*PrimeNumberDecompositionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PrimeNumberDecompositionRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PrimeNumberDecompositionResponse struct {
	PrimeFactor int32 `protobuf:"varint,1,opt,name=prime_factor,json=primeFactor" json:"prime_factor,omitempty"`
}

func (m *PrimeNumberDecompositionResponse) Reset()         { *m = PrimeNumberDecompositionResponse{} }
func (m *PrimeNumberDecompositionResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDecompositionResponse) ProtoMessage()    {}
func (*PrimeNumberDecompositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4}
}

func (m *PrimeNumberDecompositionResponse) GetPrimeFactor() int32 {
	if m != nil {
		return m.PrimeFactor
	}
	return 0
}

func init() {
	proto.RegisterType((*Numbers)(nil), "calculator.Numbers")
	proto.RegisterType((*OperationRequest)(nil), "calculator.OperationRequest")
	proto.RegisterType((*OperationResponse)(nil), "calculator.OperationResponse")
	proto.RegisterType((*PrimeNumberDecompositionRequest)(nil), "calculator.PrimeNumberDecompositionRequest")
	proto.RegisterType((*PrimeNumberDecompositionResponse)(nil), "calculator.PrimeNumberDecompositionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CalculatorService service

type CalculatorServiceClient interface {
	// Unary
	Sum(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	// Unary
	Subtract(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	// Unary
	Multiply(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error)
	// Stream
	PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberDecompositionRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDecompositionClient, error)
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	out := new(OperationResponse)
	err := grpc.Invoke(ctx, "/calculator.CalculatorService/Sum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) Subtract(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	out := new(OperationResponse)
	err := grpc.Invoke(ctx, "/calculator.CalculatorService/Subtract", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) Multiply(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	out := new(OperationResponse)
	err := grpc.Invoke(ctx, "/calculator.CalculatorService/Multiply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberDecompositionRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDecompositionClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CalculatorService_serviceDesc.Streams[0], c.cc, "/calculator.CalculatorService/PrimeNumberDecomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServicePrimeNumberDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_PrimeNumberDecompositionClient interface {
	Recv() (*PrimeNumberDecompositionResponse, error)
	grpc.ClientStream
}

type calculatorServicePrimeNumberDecompositionClient struct {
	grpc.ClientStream
}

func (x *calculatorServicePrimeNumberDecompositionClient) Recv() (*PrimeNumberDecompositionResponse, error) {
	m := new(PrimeNumberDecompositionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for CalculatorService service

type CalculatorServiceServer interface {
	// Unary
	Sum(context.Context, *OperationRequest) (*OperationResponse, error)
	// Unary
	Subtract(context.Context, *OperationRequest) (*OperationResponse, error)
	// Unary
	Multiply(context.Context, *OperationRequest) (*OperationResponse, error)
	// Stream
	PrimeNumberDecomposition(*PrimeNumberDecompositionRequest, CalculatorService_PrimeNumberDecompositionServer) error
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_Subtract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Subtract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Subtract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Subtract(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Multiply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Multiply(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_PrimeNumberDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberDecompositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).PrimeNumberDecomposition(m, &calculatorServicePrimeNumberDecompositionServer{stream})
}

type CalculatorService_PrimeNumberDecompositionServer interface {
	Send(*PrimeNumberDecompositionResponse) error
	grpc.ServerStream
}

type calculatorServicePrimeNumberDecompositionServer struct {
	grpc.ServerStream
}

func (x *calculatorServicePrimeNumberDecompositionServer) Send(m *PrimeNumberDecompositionResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
		{
			MethodName: "Subtract",
			Handler:    _CalculatorService_Subtract_Handler,
		},
		{
			MethodName: "Multiply",
			Handler:    _CalculatorService_Multiply_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecomposition",
			Handler:       _CalculatorService_PrimeNumberDecomposition_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calculator/calculatorpb/calculator.proto",
}

func init() { proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0xdd, 0xc4, 0x4d, 0x6e, 0xab, 0xb8, 0x08, 0x63, 0x0c, 0xc5, 0x2d, 0xbe, 0x0c, 0xa6,
	0x53, 0xe6, 0x93, 0x8f, 0xea, 0x14, 0x7c, 0xf0, 0x5f, 0xfb, 0xe6, 0xcb, 0x68, 0x63, 0x06, 0x81,
	0xb6, 0x89, 0xf9, 0x23, 0xec, 0x2b, 0xfb, 0x29, 0xc4, 0xa4, 0x75, 0x41, 0x28, 0x0a, 0xfa, 0xd6,
	0x7b, 0xfa, 0xbb, 0xe7, 0xdc, 0x9b, 0x04, 0x46, 0x24, 0xc9, 0x88, 0xc9, 0x12, 0xcd, 0xe5, 0xc9,
	0xea, 0x53, 0xa4, 0x5e, 0x31, 0x11, 0x92, 0x6b, 0x8e, 0x60, 0xa5, 0xe0, 0x27, 0x68, 0xdf, 0x9b,
	0x3c, 0xa5, 0x52, 0xa1, 0x21, 0x84, 0x0b, 0x26, 0x95, 0x9e, 0x17, 0x56, 0xe8, 0x35, 0x06, 0x8d,
	0x51, 0x33, 0x0a, 0xac, 0xe6, 0x18, 0x74, 0x08, 0x5b, 0x8a, 0x12, 0x5e, 0xbc, 0x54, 0x4c, 0xd3,
	0x32, 0xa1, 0x13, 0x1d, 0x84, 0x2f, 0x60, 0xe7, 0x41, 0x50, 0x99, 0x68, 0xc6, 0x8b, 0x88, 0xbe,
	0x1a, 0xaa, 0x34, 0x3a, 0x86, 0xb6, 0xeb, 0x50, 0xd6, 0x36, 0x98, 0xee, 0x4e, 0xbc, 0xb1, 0xca,
	0x09, 0xa2, 0x8a, 0xc1, 0x63, 0xe8, 0x78, 0x16, 0x4a, 0xf0, 0x42, 0x51, 0xd4, 0x85, 0x96, 0xa4,
	0xca, 0x64, 0xba, 0x9c, 0xac, 0xac, 0xf0, 0x39, 0x1c, 0x3c, 0x4a, 0x96, 0x53, 0xe7, 0x32, 0xa3,
	0x84, 0xe7, 0x82, 0x2b, 0xe6, 0xc7, 0x77, 0xa1, 0xe5, 0x2d, 0xb5, 0x11, 0x95, 0x15, 0xbe, 0x86,
	0x41, 0x7d, 0x6b, 0x19, 0x3b, 0x84, 0x50, 0x7c, 0x32, 0xf3, 0x45, 0x42, 0x34, 0xaf, 0x1c, 0x02,
	0xab, 0xdd, 0x58, 0x69, 0xfa, 0xde, 0x84, 0xce, 0xd5, 0xd7, 0x3a, 0x31, 0x95, 0x6f, 0x8c, 0x50,
	0x34, 0x83, 0xf5, 0xd8, 0xe4, 0x68, 0xcf, 0xdf, 0xf4, 0xfb, 0xc1, 0xf4, 0xf7, 0x6b, 0xfe, 0xba,
	0x70, 0xbc, 0x86, 0x6e, 0x61, 0x33, 0x36, 0xa9, 0x96, 0x09, 0xd1, 0xff, 0x60, 0x75, 0x67, 0x32,
	0xcd, 0x44, 0xb6, 0xfc, 0xab, 0xd5, 0x12, 0x7a, 0x75, 0x07, 0x87, 0xc6, 0x7e, 0xf3, 0x0f, 0x37,
	0xd3, 0x3f, 0xfa, 0x1d, 0x5c, 0x05, 0x9f, 0x36, 0x2e, 0xb7, 0x9f, 0x43, 0xff, 0x79, 0xa7, 0x2d,
	0xfb, 0xa8, 0xcf, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x34, 0x10, 0xdc, 0x00, 0x03, 0x00,
	0x00,
}
